### ISSUE TITLE
Number inside options panel.

### ISSUE THREAD

**Issue by buckett** [ToonTalk/ToonTalk#289]
I was experimenting with http://toontalk.github.io/ToonTalk/docs/manual/numbers.html?reset=1 and somehow managed to copy the number to the options panel for an existing number. When I open/close the panel the number is still there.

![screen shot 2015-05-06 at 16 59 17](https://cloud.githubusercontent.com/assets/5921/7497288/5d251928-f411-11e4-8586-062717d8fbdd.png)

**Comment by buckett** [comment]
Ah, not sure it's a bug as I can drag the number out as well.

**Comment by ToonTalk** [comment]
Admittedly this can be confusing but the idea is that you can put a number on the back of a number that a robot uses. E.g. You could train a robot to copy whatever number was on the back and add it to the current value. 

What I don't like about this design is that it can't deal with more than one number on the back. If you need that you need to put a box  on the back and put the numbers in the box.
